apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.name }}-job
spec:
  ttlSecondsAfterFinished: 7200
  template:
    metadata:
      name: {{ .Values.name }}-pod
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: hello-world
          imagePullPolicy: Always
          {{- with .Values.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      restartPolicy: OnFailure
  backoffLimit: 4
